# This is a basic workflow to help you get started with Actions

name: DeployTest

# Controls when the workflow will run
on:
  push:
    branches: [ test ]
    
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Ставим .NET
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: false

      # Публикуем
      - name: Publish .NET Core Project
        run: dotnet publish Sunduk.PWA/Sunduk.PWA.csproj -c Release --output release --nologo
          
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      
      - name: Uploading files to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-test-pages
          folder: release/wwwroot
          repository-name: dece1ver/sunduk-test
